# Generated by Django 5.1.4 on 2025-01-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_instructions_alter_item_description'),
    ]

    operations = [
       
     
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
