# Generated by Django 5.1.4 on 2025-01-20 12:59

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Om',
        ),
     
            
    
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
  
        migrations.AlterField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='customer/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='picture',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='store/'),
        ),
    ]
