# Generated by Django 5.1.4 on 2025-01-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_instructions_order_money_order_updated_at_and_more'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
