# Generated by Django 5.1.4 on 2025-02-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_instructions_store_delivery_fee_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='order',
            name='original_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True),
        ),
     
    ]
